# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_customization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='affiliation',
            field=models.CharField(blank=True, help_text='The institution(s) you belong to.', max_length=255, verbose_name='affiliation'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='city',
            field=models.CharField(blank=True, help_text='The city of your professional address.', max_length=255, verbose_name='city'),
        ),
    ]
